import type { Metadata } from "next";

export type DemoEntry = {
  slug: string;
  niche: string;
  title: string;
  description: string;
  showcase: string;
  href: string;
  pageTitle: string;
  hero: string;
  intro: string;
  locationHint: string;
  primaryCta: string;
  secondaryCta: string;
  offerLabel: string;
  heroImage?: string;
  heroImageAlt?: string;
  serviceItems: string[];
  proofItems: string[];
  processItems: string[];
};

export const demoLibrary: DemoEntry[] = [
  {
    slug: "roofing",
    niche: "Roofing",
    title: "Roofing Demo",
    description: "A bold local-service landing page built to help a roofing company turn traffic into quote requests.",
    showcase: "Clear service hierarchy, trust-oriented layout, strong mobile CTA placement, and lead-focused structure.",
    href: "/demos/roofing.html",
    pageTitle: "Roofing landing page example",
    hero: "A clean roofing page example built to turn local traffic into estimate requests.",
    intro: "This is a fictional example page that shows the kind of simple landing page Prometheus CEO could build for a roofing business.",
    locationHint: "Built for local roofing businesses",
    primaryCta: "Request a roof estimate",
    secondaryCta: "See services",
    offerLabel: "Simple landing pages starting at $197",
    serviceItems: ["Roof repair", "Roof replacement", "Storm damage", "Emergency response", "Insurance help", "Financing info"],
    proofItems: ["Service area section", "Clear quote CTA", "Trust-building layout"],
    processItems: ["Fast hero section", "Clear service list", "Simple contact flow"],
  },
  {
    slug: "dental",
    niche: "Dentist",
    title: "Dentist Demo",
    description: "A polished dental practice concept page designed to make booking feel simple and credible.",
    showcase: "Clean offer presentation, appointment-first messaging, conversion-friendly sections, and approachable visual pacing.",
    href: "/demos/dental.html",
    pageTitle: "Dentist landing page example",
    hero: "A simple dental page example focused on trust, clarity, and appointment requests.",
    intro: "This is a fictional example page that shows the kind of simple landing page Prometheus CEO could build for a dental practice.",
    locationHint: "Built for local dental practices",
    primaryCta: "Book an appointment",
    secondaryCta: "View services",
    offerLabel: "Simple landing pages starting at $197",
    serviceItems: ["Cleanings", "Whitening", "Crowns", "Family dentistry", "Emergency visits", "New patient forms"],
    proofItems: ["Simple booking flow", "Clean service overview", "Trust-focused structure"],
    processItems: ["Clear hero and CTA", "Service highlights", "Fast contact section"],
  },
  {
    slug: "chiro",
    niche: "Chiropractor",
    title: "Chiropractor Demo",
    description: "A service-page concept for a chiropractic clinic focused on clarity, trust, and easy next steps.",
    showcase: "Direct positioning, outcome-focused copy flow, local-business structure, and streamlined inquiry paths.",
    href: "/demos/chiro.html",
    pageTitle: "Chiropractor landing page example",
    hero: "A simple chiropractic page example designed to make first contact feel easy and credible.",
    intro: "This is a fictional example page that shows the kind of simple landing page Prometheus CEO could build for a chiropractic clinic.",
    locationHint: "Built for local chiropractic clinics",
    primaryCta: "Schedule a visit",
    secondaryCta: "See treatments",
    offerLabel: "Simple landing pages starting at $197",
    serviceItems: ["Back pain", "Neck pain", "Sports recovery", "Posture help", "New patient info", "Office hours"],
    proofItems: ["Outcome-first copy", "Simple trust sections", "Easy inquiry CTA"],
    processItems: ["Clear positioning", "Service breakdown", "Simple next step"],
  },
  {
    slug: "nail-salon",
    heroImage: "/demo-images/niches/nail-salon.webp",
    heroImageAlt: "Sample nail salon collage with manicure scenes.",
    niche: "Nail salon",
    title: "Nail Salon Example",
    description: "A simple nail salon example page built to show services, prices, and easy booking/contact info.",
    showcase: "Clean services section, simple hours/contact details, and a fast mobile-friendly structure.",
    href: "/examples/nail-salon",
    pageTitle: "Nail salon landing page example",
    hero: "A simple nail salon page example with a clean layout, clear services, and an easy booking path.",
    intro: "This is a fictional example for a small nail salon. It shows the kind of simple page Prometheus CEO could build for a business in this category.",
    locationHint: "Built for local nail salons",
    primaryCta: "Book an appointment",
    secondaryCta: "View services",
    offerLabel: "Simple landing pages starting at $197",
    serviceItems: ["Manicures", "Pedicures", "Gel polish", "Nail art", "Walk-ins welcome", "Hours and contact"],
    proofItems: ["Service and pricing layout", "Simple booking CTA", "Fast mobile page"],
    processItems: ["Clear intro", "Service highlights", "Simple contact block"],
  },
  {
    slug: "auto-repair",
    heroImage: "/demo-images/niches/auto-repair.webp",
    heroImageAlt: "Sample auto repair collage with mechanic and service scenes.",
    niche: "Auto repair",
    title: "Auto Repair Example",
    description: "A practical auto repair page example built to help local drivers find services, hours, and contact details fast.",
    showcase: "Straightforward service layout, trust sections, strong click-to-call CTA, and local-shop structure.",
    href: "/examples/auto-repair",
    pageTitle: "Auto repair landing page example",
    hero: "A simple auto repair page example built for a local shop that wants clear services and quick calls.",
    intro: "This is a fictional example for an independent auto repair shop. It shows the kind of simple page Prometheus CEO could build for a business in this category.",
    locationHint: "Built for local repair shops",
    primaryCta: "Request service",
    secondaryCta: "See services",
    offerLabel: "Simple landing pages starting at $197",
    serviceItems: ["Diagnostics", "Brake service", "Oil changes", "Engine repair", "Hours and location", "Call now CTA"],
    proofItems: ["Service-first layout", "Simple trust sections", "Fast contact info"],
    processItems: ["Clear headline", "Common services", "Simple call request flow"],
  },
  {
    slug: "shoe-repair",
    heroImage: "/demo-images/niches/shoe-repair.webp",
    heroImageAlt: "Sample shoe repair collage with cobbler and repair scenes.",
    niche: "Shoe repair",
    title: "Shoe Repair Example",
    description: "A compact shoe repair page example built to show repair services, turnaround notes, and direct contact details.",
    showcase: "Simple local-business structure, clear service list, and a clean mobile-friendly layout.",
    href: "/examples/shoe-repair",
    pageTitle: "Shoe repair landing page example",
    hero: "A simple shoe repair page example with clear services, hours, and direct contact info.",
    intro: "This is a fictional example for a neighborhood shoe repair shop. It shows the kind of simple page Prometheus CEO could build for a business in this category.",
    locationHint: "Built for local repair shops",
    primaryCta: "Call for a repair",
    secondaryCta: "See services",
    offerLabel: "Simple landing pages starting at $197",
    serviceItems: ["Heel repair", "Sole replacement", "Leather care", "Bag repair", "Hours and location", "Phone contact"],
    proofItems: ["Simple repair service list", "Local trust layout", "Fast contact details"],
    processItems: ["Short headline", "Repair services", "Simple call CTA"],
  },
  {
    slug: "locksmith",
    heroImage: "/demo-images/niches/locksmith.webp",
    heroImageAlt: "Sample locksmith collage with mobile locksmith service scenes.",
    niche: "Locksmith",
    title: "Locksmith Example",
    description: "A straightforward locksmith page example built to make service area, contact details, and emergency help easy to find.",
    showcase: "Fast contact CTA, simple service area structure, and clear trust-building copy.",
    href: "/examples/locksmith",
    pageTitle: "Locksmith landing page example",
    hero: "A simple locksmith page example built to make calls and service requests quick and clear.",
    intro: "This is a fictional example for a local locksmith. It shows the kind of simple page Prometheus CEO could build for a business in this category.",
    locationHint: "Built for local locksmith services",
    primaryCta: "Call for service",
    secondaryCta: "View service area",
    offerLabel: "Simple landing pages starting at $197",
    serviceItems: ["Lockouts", "Rekeying", "Lock repair", "Commercial locks", "Service area", "Phone CTA"],
    proofItems: ["Emergency-friendly layout", "Clear service sections", "Fast contact path"],
    processItems: ["Simple hero", "Service area section", "Direct call CTA"],
  },
  {
    slug: "florist",
    heroImage: "/demo-images/niches/florist.webp",
    heroImageAlt: "Sample florist collage with bouquet and flower shop scenes.",
    niche: "Florist",
    title: "Florist Example",
    description: "A clean florist page example built to show arrangements, occasions, and direct order/contact details.",
    showcase: "Simple catalog-style sections, occasion highlights, and easy contact info.",
    href: "/examples/florist",
    pageTitle: "Florist landing page example",
    hero: "A simple florist page example designed to show arrangements clearly and make ordering easy.",
    intro: "This is a fictional example for a local florist. It shows the kind of simple page Prometheus CEO could build for a business in this category.",
    locationHint: "Built for local florists",
    primaryCta: "Request an arrangement",
    secondaryCta: "See occasions",
    offerLabel: "Simple landing pages starting at $197",
    serviceItems: ["Bouquets", "Weddings", "Sympathy flowers", "Same-day requests", "Hours and contact", "Order inquiry"],
    proofItems: ["Occasion-based layout", "Simple order CTA", "Clean local-business structure"],
    processItems: ["Simple hero", "Arrangement sections", "Direct inquiry block"],
  },
  {
    slug: "acupuncture",
    heroImage: "/demo-images/niches/acupuncture.webp",
    heroImageAlt: "Sample acupuncture clinic collage with practitioner and treatment scenes.",
    niche: "Acupuncture",
    title: "Acupuncture Example",
    description: "A calm acupuncture page example built to explain treatments, build trust, and make first contact simple.",
    showcase: "Clean treatment overview, practitioner-style trust sections, and a low-friction contact flow.",
    href: "/examples/acupuncture",
    pageTitle: "Acupuncture landing page example",
    hero: "A simple acupuncture page example focused on clarity, trust, and easy first contact.",
    intro: "This is a fictional example for an acupuncture clinic. It shows the kind of simple page Prometheus CEO could build for a business in this category.",
    locationHint: "Built for local acupuncture clinics",
    primaryCta: "Book a consultation",
    secondaryCta: "View treatments",
    offerLabel: "Simple landing pages starting at $197",
    serviceItems: ["Pain relief", "Stress support", "Sleep support", "Herbal consultation", "Hours and location", "Contact form"],
    proofItems: ["Calm page structure", "Trust-oriented copy", "Simple consultation CTA"],
    processItems: ["Clear intro", "Treatment sections", "Easy inquiry step"],
  },
  {
    slug: "tattoo",
    heroImage: "/demo-images/niches/tattoo.webp",
    heroImageAlt: "Sample tattoo studio collage with artist and tattooing scenes.",
    niche: "Tattoo shop",
    title: "Tattoo Shop Example",
    description: "A simple tattoo shop example built to show style, artist info, and a clear path for inquiries.",
    showcase: "Portfolio-ready layout, strong contact section, and a fast mobile-friendly structure.",
    href: "/examples/tattoo",
    pageTitle: "Tattoo shop landing page example",
    hero: "A simple tattoo shop page example built to make inquiries and style previews easy.",
    intro: "This is a fictional example for a tattoo shop. It shows the kind of simple page Prometheus CEO could build for a business in this category.",
    locationHint: "Built for local tattoo shops",
    primaryCta: "Request an appointment",
    secondaryCta: "See styles",
    offerLabel: "Simple landing pages starting at $197",
    serviceItems: ["Custom pieces", "Flash designs", "Consultations", "Artist profiles", "Shop hours", "Inquiry CTA"],
    proofItems: ["Artist-focused sections", "Simple inquiry flow", "Clean mobile layout"],
    processItems: ["Strong hero", "Style sections", "Easy booking inquiry"],
  },
  {
    slug: "dry-cleaner",
    heroImage: "/demo-images/niches/dry-cleaner.webp",
    heroImageAlt: "Sample dry cleaner collage with garment care and customer scenes.",
    niche: "Dry cleaner",
    title: "Dry Cleaner Example",
    description: "A simple dry cleaner page example built to show services, hours, location, and direct contact info.",
    showcase: "Clean service list, straightforward trust sections, and a simple local-business layout.",
    href: "/examples/dry-cleaner",
    pageTitle: "Dry cleaner landing page example",
    hero: "A simple dry cleaner page example with clear services, hours, and local contact details.",
    intro: "This is a fictional example for a neighborhood dry cleaner. It shows the kind of simple page Prometheus CEO could build for a business in this category.",
    locationHint: "Built for local dry cleaners",
    primaryCta: "Call the shop",
    secondaryCta: "See services",
    offerLabel: "Simple landing pages starting at $197",
    serviceItems: ["Dry cleaning", "Laundry service", "Alterations", "Same-day options", "Hours and location", "Direct phone CTA"],
    proofItems: ["Simple service list", "Local trust layout", "Fast contact section"],
    processItems: ["Clear intro", "Service overview", "Simple next step"],
  },
  {
    slug: "barber",
    heroImage: "/demo-images/niches/barber.webp",
    heroImageAlt: "Sample barber shop collage with barber and grooming scenes.",
    niche: "Barber shop",
    title: "Barber Shop Example",
    description: "A simple barber shop example built to show services, hours, location, and direct booking/contact details.",
    showcase: "Simple service menu, strong local-shop feel, and clean mobile-first structure.",
    href: "/examples/barber",
    pageTitle: "Barber shop landing page example",
    hero: "A simple barber shop page example built to make hours, services, and booking easy to find.",
    intro: "This is a fictional example for a neighborhood barber shop. It shows the kind of simple page Prometheus CEO could build for a business in this category.",
    locationHint: "Built for local barber shops",
    primaryCta: "Book a cut",
    secondaryCta: "View services",
    offerLabel: "Simple landing pages starting at $197",
    serviceItems: ["Haircuts", "Beard trims", "Walk-ins", "Shop hours", "Location info", "Contact CTA"],
    proofItems: ["Service menu layout", "Simple booking CTA", "Fast local-business page"],
    processItems: ["Clear hero", "Service menu", "Direct contact section"],
  },
];

export const demoMap = Object.fromEntries(demoLibrary.map((demo) => [demo.slug, demo]));
